Repository Veronikanos/FilmotekaTeamProject, pull requests merged in 2022-12, with the labels that each got.

#29 Buttons class add-remove JS
  src/js/library-page-only/filter.js
  src/library.html
  src/library.js
  src/partials/library/header-library.html
  src/sass/base/_buttons.scss
Labels: enhancement

#42 Custom cursor on btns and links + Animation on load fix
  package-lock.json
  package.json
  src/index.html
  src/index.js
  src/js/cursor.js
  src/js/first-loading.js
  src/js/library-page-only/modal.js
  src/js/main-page-only/modal.js
  src/js/refs.js
  src/js/transitionFix.js
  src/library.html
  src/library.js
  src/partials/common/cursor.html
  src/sass/base/_buttons.scss
  src/sass/base/_common.scss
  src/sass/index.scss
  src/sass/layout/_header.scss
  src/sass/layout/_library.scss
  src/sass/layout/_main-section.scss
  src/sass/layout/_modal.scss
  src/sass/utils/_cursor.scss
  src/sass/utils/_scroll.scss
Labels: enhancement

#52 basic text for library
  src/js/library-page-only/filter.js
  src/partials/library/library.html
Labels: enhancement

#54 fixed last arrow
  src/js/main-page-only/pagination.js
  src/sass/layout/_page-numbers.scss
Labels: bug

#61 check this version
  src/js/first-loading.js
  src/js/library-page-only/filter.js
  src/js/render-markup.js
  src/sass/layout/_main-section.scss
Labels: enhancement

#62 stick footer to bot on library page
  src/sass/layout/_library.scss
Labels: enhancement

#69 Random scroll deminished
  src/js/main-page-only/pagination.js
Labels: question
